[project]
name = "ft_package"
version = "0.0.1"
authors = [{name="haeris"}, {email="haeris@student.42istanbul.com.tr"}]

description = "A sample test package"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [ ]

license = { text = "MIT" }